services:
  - type: web
    name: katz-studio
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: NODE_VERSION
        value: 18.20.7
